###The EXPOSE instruction informs Docker that the container listens on the specified network ports at runtime.
####You can specify whether the port listens on TCP or UDP, and the default is TCP if the protocol is not specified.
FROM almalinux
EXPOSE 8080/tcp

