### Entrypoint is also used to run the container like CMD, But there are few differences.
### we can't override the ENTRYPOINT, but we can override with CMD.
FROM almalinux
#CMD [ "ping", "-c5","google.com" ]
ENTRYPOINT [ "ping","-c5","google.com" ]