### ADD is same as COPY, it is useful to copy files from local to container, but it has 2 extra capabilites.
### ADD is download the file directly from internet to the container.
### ADD can untar/unzip the file directly into the container.

FROM almalinux
ADD https://github.com/veeranki2014/docker.git /tmp
ADD apache-tomcat-8.5.87.tar.gz /tmp