FROM almalinux
RUN yum install nginx -y
CMD [ "nginx", "-g", "daemon off;" ] ## CMD is the instruction that runs/executable the container

### RUN command will execute at the time of image creation.
### CMD command will execute at the time of running container.